services:
  pieczatki:
    container_name: pieczatki
    restart: always
    #    networks: [ default ]
#    ports:
#      - '80:80'
    build: .
    volumes:
      - ./:/var/www:z

networks:
  default:
    external:
      name: webproxy
