services:
  enform:
    container_name: pieczatki
    restart: unless-stopped
    networks: [ default ]
    build: .
    volumes:
      - ../:/var/www:z

networks:
  default:
    external:
      name: webproxy
