services:
  pieczatki:
    container_name: pieczatki
    restart: unless-stopped
    #    networks: [ default ]
    ports:
      - '80:80'
    build: .
    volumes:
      - ./:/var/www:z

#networks:
#  default:
#    external:
#      name: webproxy
